### PR TITLE
Risk & framework section updates

### PR DESCRIPTION
**Pull request by ltrbojevic**
This PR:

1. Add a tools & packages sub-section to the risk management section. For some early content, added Netflix's riskquant
2. Adds FedRAMP and 800-171 to the frameworks section, batches the public sector stuff at the bottom, and renames AICPA to SOC (so the framework is listed over the accrediting body)

### CODE REVIEW

**Comment by veritysecurity** [comment]
I differ on what is called a framework and what should be categorized as control sets. In your current list is NIST SP 800-39, which is for the management of risk and not the framework. This should be changed to NIST SP 800-37r2 which is the central document for the NIST Risk Management Framework. (I still debate if this is a true framework but I'm just going with it).

FedRAMP and 800-171 are control sets and not frameworks. 800-171 is actually a subset of 800-53 which is a control set included within the NIST RMF.

A control catalog is a group of accepted organizational controls comprised from various control sets. (The 800-53 is designated as a control catalog in that document but that has reference to the FISMA requirements. A private company may have a different control catalog which may include NIST in their control catalog).

**Comment by ltrbojevic** [comment]
Agreed - just noting @Arudjreis is the author of this resource, not me. I'm just proposing content additions based on what's already in there :D

I think it would be great to get a PR from you to semantically tighten some of the headers and content groupings

**Comment by veritysecurity** [comment]
Thanks for clarifying. More content is great. I am a systems/analyst guy so organizing content is my focus.
I would like to participate. I am not a frequent GitHub user. What is a PR?

**Comment by Arudjreis** [comment]
Thanks both for the output. I really enjoy having some feedback and precision regarding terminology and semantics, 

I'll fully review the PR tomorrow, most of the frameworks and regulations content wasn't added by me but came from a previous PR. 

There's so much to do that I didn't do a full review yet. 

Thanks a lot for the contribution!

**Comment by Arudjreis** [comment]
As a side note I'm French and now UK-based. My knowledge of US control sets, frameworks and regulations is very scarce so I'll need a lot of input from SMEs from across the Atlantic.

**Comment by veritysecurity** [comment]
I am glad to help. The content looks good right now. I have already benefited from the references. Thanks for your work.

Kent Pankratz | Cyber Security Consultant
Verity Security LLC | https://www.veritysecurity.com
Mobile: 6082069273 | ***@***.******@***.***>

**Comment by ryanmrestivo** [comment]
I think it would be appropriate to sub-categorize the framework and control sets.  The larger consideration is how "deep" the control sets within the frameworks are defined in the "top-level" of the guide.  In NIST SP 800 (Special Publications) there are currently 192 volumes.  There are also other control sets with varying applicability to NIST and US Gov systems.
FIPS
All SP series
NISTIRs
ITL Bulletins

It probably isn't feasible to include many control sets (long term) on the main page of the repo.  @Ayoub do you eventually want to have the awesome-security-GRC repo have multiple sub-folders?  Or have the "top-level" only link out to other repositories/resources?

**Comment by Arudjreis** [comment]
To be honest I haven't given any thoughts to this. 

Let's focus on making the repo better little by little. I still want it to be a one-pager for ease of referencing and maintaining as well.

**Pull request merged**
